print ("Hello World")
print ("Hello friend")
print ("Hello now")
print ("Hello")
print (2+2)
print(type("Hello, World!"))
print(len ("Hello world"))
print(2*6)
print(type("Hello world"))
pi=3.1459
print(pi*6)
minutes=645
hours=minutes//60
print(hours)
print (int(3.56))
print (float(173))
print (str(196))
n=input("Please enter your name")
print (5%2)
print (15%12)